#pragma once


enum ERR
{
    USAGE_ERR = 1,
    SOCK_ERR,
    BIND_ERR,
    LISTEN_ERR,
    CONNECT_ERR,
    ACCEPT_ERR,
    EPOLL_CREATE_ERR,
    SOCK_SET_NONBLOCK_ERR,
    SOCK_READ_MINITOR_ERR,
    EVENTFD_CREATE_ERR,
    EVENTFD_READ_ERR,
    EVENTFD_WRITE_ERR,
    EVENTFD_READ_MINITOR_ERR,
    TIMERFD_CREATE_ERR,
    TIMERFD_READ_ERR,
    TIMERFD_WRITE_ERR,
    TIMERFD_READ_MINITOR_ERR
};